name = "PDMP"
uuid = "ddd15e80-e4be-11e8-272b-c1c647be5ca8"
authors = ["Romain Veltz <rveltz@salk.edu>", " Simon Frost <sdf22@cam.ac.uk>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
