name = "PiecewiseDeterministicMarkovProcesses"
uuid = "86206cdf-4603-54e0-bd58-22a2dcbf57aa"
authors = ["Romain Veltz <rveltz@salk.edu>", " Simon Frost <sdf22@cam.ac.uk>"]
version = "0.0.6"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DifferentialEquations = "6, ^7"
Distributions = "0.23, 0.24, 0.25"
ForwardDiff = "0.10"
LSODA = "0.6.2, 0.7"
Parameters = "0.12"
PreallocationTools = "^0.4"
RecursiveArrayTools = "2.8, 2.9"
StatsBase = "0.33"
Sundials = "4.5, 4.6, 4.7, 4.8, 4.9"
julia = "1.3, 1.4, 1.5, 1.6, 1.7"
JumpProcesses = "^9.2"
SciMLBase = "^1.59"